name: fuels_beta3
description: Dart FFI bridge to Fuel Rust SDK for beta-3
version: 1.2.0
homepage: https://github.com/Fuelet/fuels-dart-beta3/tree/main/packages/fuels_beta3

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: 1.75.3
  uuid: ^3.0.7 # must be compatible with flutter_rust_bridge version
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
  collection: ^1.17.0

dev_dependencies:
  test: ^1.24.2
  lints: ^2.0.0
  ffigen: ^7.2.11
  freezed: ^2.3.2
  build_runner: ^2.3.2
